package com.example.entity;
// Generated Sep 22, 2020, 4:33:45 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String username;
	private String lastname;
	private String firstname;
	private String role;
	private int age;
	private Date dateOfBirth;
	private String email;
	private Date dayOfRegistration;
	private String password;

	public User() {
	}

	public User(String username, String lastname, String firstname, String role, int age, Date dateOfBirth,
			String email, String password) {
		this.username = username;
		this.lastname = lastname;
		this.firstname = firstname;
		this.role = role;
		this.age = age;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.password = password;
	}

	public User(String username, String lastname, String firstname, String role, int age, Date dateOfBirth,
			String email, Date dayOfRegistration, String password) {
		this.username = username;
		this.lastname = lastname;
		this.firstname = firstname;
		this.role = role;
		this.age = age;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.dayOfRegistration = dayOfRegistration;
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDayOfRegistration() {
		return this.dayOfRegistration;
	}

	public void setDayOfRegistration(Date dayOfRegistration) {
		this.dayOfRegistration = dayOfRegistration;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
